spring:
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: database/liquibase-changelog-test.xml
email-info-queue: info-email
info-queue: info
performance-info-queue: info-performance